/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2025-01-21 16:29:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("	<!-- *****************************************************************************************************************\n");
      out.write("	 FOOTER\n");
      out.write("	 ***************************************************************************************************************** -->\n");
      out.write("	 <div id=\"footerwrap\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-4\">\n");
      out.write("                    <h4>About</h4>\n");
      out.write("                    <div class=\"hline-w\"></div>\n");
      out.write("                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-4\">\n");
      out.write("                    <h4>Social Links</h4>\n");
      out.write("                    <div class=\"hline-w\"></div>\n");
      out.write("                    <p>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-tumblr\"></i></a>\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-4\">\n");
      out.write("                    <h4>Our Bunker</h4>\n");
      out.write("                    <div class=\"hline-w\"></div>\n");
      out.write("                    <p>\n");
      out.write("                        Some Ave, 987,<br/>\n");
      out.write("                        23890, New York,<br/>\n");
      out.write("                        United States.<br/>\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            \n");
      out.write("            </div><! --/row -->\n");
      out.write("        </div><! --/container -->\n");
      out.write("    </div><! --/footerwrap -->\n");
      out.write("    \n");
      out.write("   <!-- Bootstrap core JavaScript\n");
      out.write("   ================================================== -->\n");
      out.write("   <!-- Placed at the end of the document so the pages load faster -->\n");
      out.write("   <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js\"></script>\n");
      out.write("   <script src=\"assets/js/bootstrap.min.js\"></script>\n");
      out.write("   <script src=\"assets/js/retina-1.1.0.js\"></script>\n");
      out.write("   <script src=\"assets/js/jquery.hoverdir.js\"></script>\n");
      out.write("   <script src=\"assets/js/jquery.hoverex.min.js\"></script>\n");
      out.write("   <script src=\"assets/js/jquery.prettyPhoto.js\"></script>\n");
      out.write("     <script src=\"assets/js/jquery.isotope.min.js\"></script>\n");
      out.write("     <script src=\"assets/js/custom.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("   <script>\n");
      out.write("// Portfolio\n");
      out.write("(function($) {\n");
      out.write("   \"use strict\";\n");
      out.write("   var $container = $('.portfolio'),\n");
      out.write("       $items = $container.find('.portfolio-item'),\n");
      out.write("       portfolioLayout = 'fitRows';\n");
      out.write("       \n");
      out.write("       if( $container.hasClass('portfolio-centered') ) {\n");
      out.write("           portfolioLayout = 'masonry';\n");
      out.write("       }\n");
      out.write("               \n");
      out.write("       $container.isotope({\n");
      out.write("           filter: '*',\n");
      out.write("           animationEngine: 'best-available',\n");
      out.write("           layoutMode: portfolioLayout,\n");
      out.write("           animationOptions: {\n");
      out.write("           duration: 750,\n");
      out.write("           easing: 'linear',\n");
      out.write("           queue: false\n");
      out.write("       },\n");
      out.write("       masonry: {\n");
      out.write("       }\n");
      out.write("       }, refreshWaypoints());\n");
      out.write("       \n");
      out.write("       function refreshWaypoints() {\n");
      out.write("           setTimeout(function() {\n");
      out.write("           }, 1000);   \n");
      out.write("       }\n");
      out.write("               \n");
      out.write("       $('nav.portfolio-filter ul a').on('click', function() {\n");
      out.write("               var selector = $(this).attr('data-filter');\n");
      out.write("               $container.isotope({ filter: selector }, refreshWaypoints());\n");
      out.write("               $('nav.portfolio-filter ul a').removeClass('active');\n");
      out.write("               $(this).addClass('active');\n");
      out.write("               return false;\n");
      out.write("       });\n");
      out.write("       \n");
      out.write("       function getColumnNumber() { \n");
      out.write("           var winWidth = $(window).width(), \n");
      out.write("           columnNumber = 1;\n");
      out.write("       \n");
      out.write("           if (winWidth > 1200) {\n");
      out.write("               columnNumber = 5;\n");
      out.write("           } else if (winWidth > 950) {\n");
      out.write("               columnNumber = 4;\n");
      out.write("           } else if (winWidth > 600) {\n");
      out.write("               columnNumber = 3;\n");
      out.write("           } else if (winWidth > 400) {\n");
      out.write("               columnNumber = 2;\n");
      out.write("           } else if (winWidth > 250) {\n");
      out.write("               columnNumber = 1;\n");
      out.write("           }\n");
      out.write("               return columnNumber;\n");
      out.write("           }       \n");
      out.write("           \n");
      out.write("           function setColumns() {\n");
      out.write("               var winWidth = $(window).width(), \n");
      out.write("               columnNumber = getColumnNumber(), \n");
      out.write("               itemWidth = Math.floor(winWidth / columnNumber);\n");
      out.write("               \n");
      out.write("               $container.find('.portfolio-item').each(function() { \n");
      out.write("                   $(this).css( { \n");
      out.write("                   width : itemWidth + 'px' \n");
      out.write("               });\n");
      out.write("           });\n");
      out.write("       }\n");
      out.write("       \n");
      out.write("       function setPortfolio() { \n");
      out.write("           setColumns();\n");
      out.write("           $container.isotope('reLayout');\n");
      out.write("       }\n");
      out.write("           \n");
      out.write("       $container.imagesLoaded(function () { \n");
      out.write("           setPortfolio();\n");
      out.write("       });\n");
      out.write("       \n");
      out.write("       $(window).on('resize', function () { \n");
      out.write("       setPortfolio();          \n");
      out.write("   });\n");
      out.write("})(jQuery);\n");
      out.write("</script>\n");
      out.write(" </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
